- import_tasks: uninstall.yml
- import_tasks: uninstall-kdc.yml
- import_tasks: install.yml
- import_tasks: install-kdc.yml
  when: (ambari.enable_kerberos == true)
- import_tasks: deploy.yml

- import_tasks: patch.yml
  when: (ambari.enable_kerberos == true)
