# copy and install toree
 - debug:
    msg: "Downloading Toree:  {{ notebook.toree_pip_download_location }}{{ notebook.toree_archive_package_name }}"

 - name: download toree
   local_action: get_url url="{{ notebook.toree_pip_download_location }}{{ notebook.toree_archive_package_name }}" dest="/tmp"
   run_once: true

 - name: copy toree to remote node
   copy:
     src: "/tmp/{{ notebook.toree_archive_package_name }}"
     dest: "{{ install_temp_dir }}/{{ notebook.toree_archive_package_name }}"

 - name: pip uninstall toree
   shell: "{{ pip }} uninstall -y {{ notebook.toree_archive_package_name }}"
   ignore_errors: yes

 - name: pip install toree
   shell: "{{ pip }} install --upgrade {{ install_temp_dir }}/{{notebook.toree_archive_package_name}}"
   ignore_errors: yes

 - debug:
    msg: "{{ jupyter }} toree install --spark_home={{ notebook.spark_home}} --kernel_name=\"Spark 2.1\" --interpreters=Scala"

 - name: install toree kernel
   shell: >
    {{ jupyter }} toree install --spark_home={{ notebook.spark_home}} --kernel_name="Spark 2.1" --interpreters=Scala
   ignore_errors: yes

 - name: retrieve kernelspec location
   shell: "/opt/anaconda2/bin/jupyter kernelspec list | grep -w spark_2.1_scala | awk '{print $2}' | xargs -i dirname {}"
   register: result

 - name: store kernelspec location
   set_fact: jupyter_kernelspec_location="{{ result.stdout }}"
   with_items: "{{ result.stdout }}"

 - name: remove old kernelspecs for yarn cluster
   file:
     path: "{{ jupyter_kernelspec_location }}/spark_scala_yarn_cluster"
     state: absent

 - name: remove old kernelspecs for yarn client
   file:
     path: "{{ jupyter_kernelspec_location }}/spark_scala_yarn_client"
     state: absent

 - name: seed kernelspec location for yarn cluster
   shell: "cp -r {{ jupyter_kernelspec_location }}/spark_2.1_scala/ {{ jupyter_kernelspec_location }}/spark_scala_yarn_cluster"
   ignore_errors: yes

 - name: seed kernelspec location for yarn client
   shell: "cp -r {{ jupyter_kernelspec_location }}/spark_2.1_scala/ {{ jupyter_kernelspec_location }}/spark_scala_yarn_client"
   ignore_errors: yes

 - name: remove source kernelspecs location
   file:
     path: "{{ jupyter_kernelspec_location }}/spark_2.1_scala"
     state: absent

 - name: update kernel launcher for yarn cluster
   shell: "tar -zxvf {{ install_temp_dir }}/{{ notebook.elyra_kernelspec_package_name }} --strip 1 --directory {{ jupyter_kernelspec_location }}/spark_scala_yarn_cluster/ spark_scala_yarn_cluster/"
   ignore_errors: yes

 - name: update kernel launcher for yarn client
   shell: "tar -zxvf {{ install_temp_dir }}/{{ notebook.elyra_kernelspec_package_name }} --strip 1 --directory {{ jupyter_kernelspec_location }}/spark_scala_yarn_client/ spark_scala_yarn_client/"
   ignore_errors: yes

 - name: disable impersonation based on configuration (only applies to cluster mode)
   shell: " sed -i 's/ --proxy-user ${KERNEL_USERNAME:-ERROR__NO__KERNEL_USERNAME}//g' {{ jupyter_kernelspec_location }}/spark_scala_yarn_cluster/kernel.json"
   ignore_errors: yes
   when: (notebook.enable_impersonation == false)
