# Create temporary install folders
# this is required mostly when these
# scripts are mainly used to update
# Enterprise Gateway deployment
- name: create install dir
  file: path="{{ install_dir }}" state=directory

- name: remove old temporary install dir
  file: path="{{ install_temp_dir }}" state=absent

- name: create temporary install dir
  file: path="{{ install_temp_dir }}" state=directory
  when: (inventory_hostname in groups['master']) or (notebook.deploy_kernelspecs_to_workers == true)

#

- name: set pip location
  set_fact: pip={{ install_dir }}/anaconda{{ python_version }}/bin/pip
  when: notebook.use_anaconda

- name: set pip location
  set_fact: pip=pip
  when: not notebook.use_anaconda

- name: set jupyter location
  set_fact: jupyter={{ install_dir }}/anaconda{{ python_version }}/bin/jupyter
  when: notebook.use_anaconda

- name: set jupyter location
  set_fact: jupyter=jupyter
  when: not notebook.use_anaconda

- name: set RScript location
  set_fact: rscript={{ install_dir }}/anaconda{{ python_version }}/bin/RScript
  when: notebook.use_anaconda

- name: set RScript location
  set_fact: rscript=Rscript
  when: not notebook.use_anaconda

- include: dependencies.yml

- include: gateway.yml

- include: kernel_scala.yml
  when: (inventory_hostname in groups['master']) or (notebook.deploy_kernelspecs_to_workers == true) 

- include: kernel_python.yml
  when: (inventory_hostname in groups['master']) or (notebook.deploy_kernelspecs_to_workers == true) 

- include: kernel_R.yml
