#- name: Create service account for Spark
#  user: name={{ spark.user }}
#        system=yes
#        shell={{ spark.user_shell }}
#        state=present
#        groups="{{ spark.user_groups | join(',') }}"

- name: set spark fact
  set_fact: spark_installed=True

- name: set spark installation path fact
  set_fact: spark_installation_dir=spark-{{ spark.version }}-bin-hadoop{{ spark.hadoop_version }}

- name: set spark archive fact
  set_fact: spark_archive=spark-{{ spark.version }}-bin-hadoop{{ spark.hadoop_version }}.tgz

- name: set spark download location fact
  set_fact: spark_download={{ spark.download_location }}

- name: define number of spark workers
  set_fact: number_of_workers="{{ groups['nodes'] | length | int }}"

- name: create install directory
  file:
    path: "{{ install_dir }}/{{ spark_installation_dir }}"
    state: directory
#    owner: "{{ spark.user }}"
#    group: "{{ spark.user }}"
#  become: true

- name: stop spark
  shell: "sbin/stop-all.sh"
  args:
      chdir: "{{ install_dir}}/{{ spark_installation_dir }}"
  ignore_errors: yes
  when: inventory_hostname in groups['master']


- debug:
     msg: "Downloading Spark from: {{ spark_download }}"

- name: download spark
  get_url: url="{{ spark_download }}" dest="{{ install_temp_dir }}/{{ spark_archive }}"

- name: unarchive to the install directory
  shell: "tar -xvf {{ install_temp_dir }}/{{ spark_archive }} --strip 1 --directory {{ install_dir }}/{{ spark_installation_dir }}"


- name: create spark working directory
  file:
    path: "{{ spark.working_dir }}"
    state: directory
#    owner: "{{ spark.user }}"
#    group: "{{ spark.user }}"
#  become: true

- name: set spark-env.sh
  template: src="spark-env-sh.j2" dest="{{ install_dir }}/{{ spark_installation_dir }}/conf/spark-env.sh"

- name: set spark-defaults.conf
  template: src="spark-defaults-conf.j2" dest="{{ install_dir}}/{{ spark_installation_dir }}/conf/spark-defaults.conf"

- name: set slaves
  template: src="slaves.j2" dest="{{ install_dir}}/{{ spark_installation_dir }}/conf/slaves"

# Environment setup.
- name: add spark profile to startup
  template:
    src: spark-profile.sh.j2
    dest: /etc/profile.d/spark-profile.sh
    mode: 0644

- name: set conda download location fact
  set_fact: conda_download={{ spark.conda_download_location }}

- name: create install directory
  file:
    path: "{{ install_dir }}/python"
    state: directory

- name: download conda
  get_url: url="{{ conda_download }}" dest="{{ install_temp_dir }}/miniconda.sh"

- name: install conda
  shell: "bash {{ install_temp_dir }}/miniconda.sh -b -p {{ install_dir }}/python/miniconda3"
  ignore_errors: yes

- name: create env for spark
  shell: "{{ install_dir }}/python/miniconda3/bin/conda create -n spark python=3.8.5 -y"
  ignore_errors: yes

- name: set requirements
  template: src="requirements.txt.j2" dest="{{ install_dir}}/python/requirements.txt"

- name: install requirements
  shell: "{{ install_dir }}/python/miniconda3/envs/spark/bin/pip install -r {{ install_dir}}/python/requirements.txt"



