- name: install commonly used os dependencies
  shell:
     yum install -y unzip bzip2 gcc openssl-devel libffi-devel python-devel openssl-devel libcurl libcurl-devel

- name: upgrade all packages
  shell:
     yum update -y

- name: clean yum repository
  shell: "yum clean all"